package org.appliedtopology.tda4j
package groups

import scala.collection.mutable

/** A finite group as a multiplication table on the elements `0 until order`, with `0` the identity.
  *
  * Deliberately the dumbest possible representation: the nerve construction (`ClassifyingSpace`) only ever multiplies
  * and asks "is this the identity?", and a table makes both an array lookup. Fine up to a few hundred elements (S_5 has
  * 120: a 14,400-entry table).
  */
final class FiniteGroup(val table: Array[Array[Int]], val names: IndexedSeq[String]):
  def order: Int = table.length
  def identity: Int = 0
  def multiply(a: Int, b: Int): Int = table(a)(b)

  def inverse(a: Int): Int = table(a).indexOf(identity)

  /** Checks identity, closure, associativity and inverses; the empty list means the table really is a group. */
  def validate(): Seq[String] =
    val n = order
    val shape = if table.exists(_.length != n) then Seq("table is not square") else Seq.empty
    if shape.nonEmpty then shape
    else
      val range = table.flatten.filter(x => x < 0 || x >= n).take(1).map(x => s"entry $x out of range")
      val unit = (0 until n).filter(a => table(0)(a) != a || table(a)(0) != a).take(1).map(a => s"0 is not an identity at $a")
      val inv = (0 until n).filter(a => !table(a).contains(0)).take(1).map(a => s"$a has no inverse")
      val assoc =
        (for a <- 0 until n; b <- 0 until n; c <- 0 until n if table(table(a)(b))(c) != table(a)(table(b)(c))
        yield s"not associative at ($a,$b,$c)").take(1)
      range ++ unit ++ inv ++ assoc

  /** The subgroup generated by `generators` (as a set of element indices; always contains the identity). */
  def subgroupGeneratedBy(generators: Iterable[Int]): Set[Int] =
    val members = mutable.LinkedHashSet[Int](identity)
    val queue = mutable.Queue[Int](identity)
    while queue.nonEmpty do
      val x = queue.dequeue()
      for g <- generators do
        val y = multiply(x, g)
        if members.add(y) then queue.enqueue(y)
    members.toSet

object FiniteGroup:

  def cyclic(n: Int): FiniteGroup =
    require(n >= 1)
    FiniteGroup(Array.tabulate(n, n)((a, b) => (a + b) % n), IndexedSeq.tabulate(n)(i => s"g^$i"))

  /** Direct product; element `(a, b)` is indexed `a * order(h) + b`, so the identity stays `0`. */
  def product(g: FiniteGroup, h: FiniteGroup): FiniteGroup =
    val m = h.order
    FiniteGroup(
      Array.tabulate(g.order * m, g.order * m)((x, y) => g.multiply(x / m, y / m) * m + h.multiply(x % m, y % m)),
      IndexedSeq.tabulate(g.order * m)(x => s"(${g.names(x / m)},${h.names(x % m)})")
    )

  /** The group generated by permutations of `0 until degree` (each given as the image list `p(0), p(1), ...`),
    * together with the generators' element indices. Composition is `(p * q)(x) = p(q(x))`.
    */
  def permutationGroup(degree: Int, generators: Seq[Seq[Int]]): (FiniteGroup, Seq[Int]) =
    val id = Vector.range(0, degree)
    def compose(p: Vector[Int], q: Vector[Int]): Vector[Int] = q.map(p)
    val gens = generators.map(_.toVector)
    val elements = mutable.ArrayBuffer[Vector[Int]](id)
    val index = mutable.HashMap[Vector[Int], Int](id -> 0)
    var next = 0
    while next < elements.length do
      for g <- gens do
        val y = compose(elements(next), g)
        if !index.contains(y) then
          index(y) = elements.length
          elements += y
      next += 1
    val table = Array.tabulate(elements.length, elements.length)((a, b) => index(compose(elements(a), elements(b))))
    val names = elements.map(p => cycleNotation(p)).toIndexedSeq
    (FiniteGroup(table, names), gens.map(g => index.getOrElse(g, throw IllegalArgumentException("not a permutation"))))

  /** The symmetric group S_n, generated by the transposition (0 1) and the n-cycle. */
  def symmetric(n: Int): FiniteGroup =
    require(n >= 2)
    val transposition = Vector.range(0, n).updated(0, 1).updated(1, 0)
    val cycle = Vector.tabulate(n)(i => (i + 1) % n)
    permutationGroup(n, Seq(transposition, cycle))._1

  /** The element of `g` (a permutation group built by [[permutationGroup]]) that has this image list. */
  def elementOfPermutation(g: FiniteGroup, p: Seq[Int]): Int =
    val wanted = cycleNotation(p.toVector)
    val i = g.names.indexOf(wanted)
    require(i >= 0, s"$wanted is not an element of the group")
    i

  private def cycleNotation(p: Vector[Int]): String =
    val seen = Array.fill(p.length)(false)
    val cycles = for
      start <- p.indices
      if !seen(start) && p(start) != start
    yield
      val cycle = Iterator.iterate(start)(p).takeWhile { x => val fresh = !seen(x); seen(x) = true; fresh }.toList
      cycle.mkString("(", " ", ")")
    if cycles.isEmpty then "e" else cycles.mkString
