package org.appliedtopology.tda4j
package cells

import org.appliedtopology.tda4j.algebra.{given, *}

/** A generator of the cone on a simplicial set `X`: the apex, a copy of each generator of `X` (the base), or the cone
  * `Cone(g)` over a generator `g` (one dimension up).
  */
enum ConeGenerator[+G]:
  case Apex
  case Base(g: G)
  case Cone(g: G)

object ConeGenerator:
  given coneGeneratorOrdering: [G: Ordering as ord] => Ordering[ConeGenerator[G]]:
    private def key(c: ConeGenerator[G]): (Int, Option[G]) = c match
      case ConeGenerator.Apex    => (0, None)
      case ConeGenerator.Base(g) => (1, Some(g))
      case ConeGenerator.Cone(g) => (2, Some(g))
    private val keyOrdering: Ordering[(Int, Option[G])] =
      Ordering.Tuple2(using Ordering.Int, Ordering.Option(using ord))
    def compare(x: ConeGenerator[G], y: ConeGenerator[G]): Int = keyOrdering.compare(key(x), key(y))

/** Ready-made finite simplicial sets and constructions on them (the Sage `simplicial_sets.*` gap list; see
  * `.claude/DESIGN-sage-simplicial-sets-comparison.md`). Everything here is additive and finite; pullbacks and integer
  * coefficients are deliberately not here.
  *
  * Complexes given by vertices use [[Simplex]]`[Int]` as the generator type; the faces of a simplex are `d_i` = omit
  * its `i`-th vertex, so the simplicial identities hold automatically.
  */
object SimplicialSets:
  import ConeGenerator.*

  /** The simplicial set of the abstract simplicial complex generated by `facets` (every nonempty face of a facet is a
    * generator). Vertices need not be `0..n`; their natural order orients each simplex.
    */
  def fromSimplicialComplex(facets: Iterable[Simplex[Int]]): FiniteSimplicialSet[Simplex[Int]] =
    val all: Set[Simplex[Int]] = facets.iterator.flatMap { facet =>
      val vertices = facet.toList
      (1 to vertices.size).iterator.flatMap(k => vertices.combinations(k).map(c => Simplex.from(c)))
    }.toSet
    val top = if all.isEmpty then -1 else all.map(_.dim).max
    val byDim = IndexedSeq.tabulate(top + 1)(d => all.filter(_.dim == d))
    def faces(s: Simplex[Int]): IndexedSeq[SSetElement[Simplex[Int]]] =
      if s.dim == 0 then IndexedSeq.empty
      else s.toList.indices.map(i => SSetElement(Nil, Simplex.from(s.toList.patch(i, Nil, 1)))).toIndexedSeq
    new FiniteSimplicialSet(byDim, faces)

  /** The standard `n`-simplex `Δ^n` (all faces of `{0..n}`); contractible. */
  def simplex(n: Int): FiniteSimplicialSet[Simplex[Int]] =
    require(n >= 0)
    fromSimplicialComplex(Seq(Simplex.from((0 to n).toList)))

  /** A single point. */
  def point: FiniteSimplicialSet[Simplex[Int]] = simplex(0)

  /** The empty simplicial set (no generators in any dimension). */
  def empty: FiniteSimplicialSet[Simplex[Int]] = fromSimplicialComplex(Seq.empty)

  /** The horn `Λ^n_k`: `Δ^n` without its interior and without its `k`-th facet (the one omitting vertex `k`); a
    * contractible set.
    */
  def horn(n: Int, k: Int): FiniteSimplicialSet[Simplex[Int]] =
    require(n >= 1 && k >= 0 && k <= n)
    fromSimplicialComplex((0 to n).filter(_ != k).map(i => Simplex.from((0 to n).filter(_ != i).toList)))

  enum KleinGenerator derives CanEqual:
    case V, A, B, C, T1, T2

  object KleinGenerator:
    given Ordering[KleinGenerator] = Ordering.by(_.ordinal)

  /** The Klein bottle as a Δ-complex with one vertex, edges `a, b, c` and two triangles whose faces `(d_0, d_1, d_2)`
    * are `(b, c, a)` and `(a, b, c)`. Derived by hand: `π_1 = <a, b | a b a = b>` (Klein group), `∂T1 = a + b - c`,
    * `∂T2 = a - b + c` give `H_1 = Z ⊕ Z/2`, `H_2 = 0` -- so Betti numbers `(1, 2, 1)` over `F_2` and `(1, 1, 0)` over
    * `F_3`, which is what distinguishes it from the torus.
    */
  def kleinBottle: FiniteSimplicialSet[KleinGenerator] =
    import KleinGenerator.*
    def v(g: KleinGenerator) = SSetElement[KleinGenerator](Nil, g)
    def facesOf(g: KleinGenerator): IndexedSeq[SSetElement[KleinGenerator]] = g match
      case V         => IndexedSeq.empty
      case A | B | C => IndexedSeq(v(V), v(V))
      case T1        => IndexedSeq(v(B), v(C), v(A))
      case T2        => IndexedSeq(v(A), v(B), v(C))
    new FiniteSimplicialSet(IndexedSeq(Set(V), Set(A, B, C), Set(T1, T2)), facesOf)

  /** The sub-simplicial set on `keep` -- which must be closed under taking faces. */
  def subcomplex[G](sset: FiniteSimplicialSet[G], keep: Set[G]): FiniteSimplicialSet[G] =
    for g <- keep; face <- sset.faces(g) do
      require(keep.contains(face.generator), s"subcomplex: $g is kept but its face generator ${face.generator} is not")
    val byDim = sset.generatorsByDim.map(_.filter(keep.contains))
    new FiniteSimplicialSet(byDim.reverse.dropWhile(_.isEmpty).reverse, sset.faces)(using sset.ord)

  /** The unreduced cone `CX = X ⋆ pt`: apex last, so `d_{n+1} Cone(g) = g` and `d_i Cone(g) = Cone(d_i g)` (a
    * degenerate face `s_J h` becomes `s_J Cone(h)`: no degeneracy ever touches the apex). Contractible.
    */
  def cone[G](x: FiniteSimplicialSet[G]): FiniteSimplicialSet[ConeGenerator[G]] =
    given Ordering[G] = x.ord
    val byDim: IndexedSeq[Set[ConeGenerator[G]]] =
      IndexedSeq.tabulate(x.generatorsByDim.length + 1) { d =>
        val base: Set[ConeGenerator[G]] = x.generatorsAt(d).map(g => Base(g): ConeGenerator[G]).toSet
        val cones: Set[ConeGenerator[G]] = x.generatorsAt(d - 1).map(g => Cone(g): ConeGenerator[G]).toSet
        (if d == 0 then Set[ConeGenerator[G]](Apex) else Set.empty[ConeGenerator[G]]) ++ base ++ cones
      }
    def mapped(e: SSetElement[G])(wrap: G => ConeGenerator[G]): SSetElement[ConeGenerator[G]] =
      SSetElement(e.word, wrap(e.generator))
    def facesOf(g: ConeGenerator[G]): IndexedSeq[SSetElement[ConeGenerator[G]]] = g match
      case Apex    => IndexedSeq.empty
      case Base(h) => x.faces(h).map(mapped(_)(Base(_)))
      case Cone(h) =>
        val n = x.dimOf(h)
        if n == 0 then IndexedSeq(SSetElement(Nil, Apex), SSetElement(Nil, Base(h)))
        else x.faces(h).map(mapped(_)(Cone(_))) :+ SSetElement(Nil, Base(h))
    new FiniteSimplicialSet(byDim, facesOf)

  /** The unreduced suspension `SX`: two cones on `X` glued along their common base. */
  def suspension[G](x: FiniteSimplicialSet[G]): FiniteSimplicialSet[Either[ConeGenerator[G], ConeGenerator[G]]] =
    given Ordering[G] = x.ord
    val c = cone(x)
    val both = FiniteSimplicialSet.coproduct(c, c)
    given Ordering[Either[ConeGenerator[G], ConeGenerator[G]]] = both.ord
    val glue = x.generatorsByDim.flatten.toSeq.map { g =>
      (
        Left(Base(g)): Either[ConeGenerator[G], ConeGenerator[G]],
        Right(Base(g)): Either[ConeGenerator[G], ConeGenerator[G]]
      )
    }
    FiniteSimplicialSet.identify(both, glue)

  /** The wedge `X ∨ Y` at the vertices `vx` of `X` and `vy` of `Y` (a base point is just a chosen vertex). */
  def wedge[GX, GY](
    x: FiniteSimplicialSet[GX],
    vx: GX,
    y: FiniteSimplicialSet[GY],
    vy: GY
  ): FiniteSimplicialSet[Either[GX, GY]] =
    require(x.dimOf(vx) == 0 && y.dimOf(vy) == 0, "wedge points must be vertices")
    given Ordering[GX] = x.ord
    given Ordering[GY] = y.ord
    val both = FiniteSimplicialSet.coproduct(x, y)
    given Ordering[Either[GX, GY]] = both.ord
    FiniteSimplicialSet.identify(both, Seq((Left(vx): Either[GX, GY], Right(vy): Either[GX, GY])))

  /** Non-degenerate simplex counts per dimension (Sage's `f_vector`). */
  def fVector[G](x: FiniteSimplicialSet[G]): Vector[Int] = x.generatorsByDim.map(_.size).toVector

  /** Whether the 1-skeleton is connected (the empty set counts as not connected). */
  def isConnected[G](x: FiniteSimplicialSet[G]): Boolean =
    val vertices = x.generatorsAt(0).toVector
    if vertices.isEmpty then false
    else
      val parent = scala.collection.mutable.Map.from(vertices.map(v => v -> v))
      def find(v: G): G = if parent(v) == v then v
      else
        val r = find(parent(v)); parent(v) = r; r
      for e <- x.generatorsAt(1) do
        val ends = x.faces(e).map(f => find(f.generator))
        if ends(0) != ends(1) then parent(ends(0)) = ends(1)
      vertices.map(find).distinct.size == 1
