addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"             % "1.4.1")
addSbtPlugin("io.kevinlee"      % "sbt-github-pages"     % "0.10.0")
addSbtPlugin("com.typesafe"     % "sbt-mima-plugin"      % "0.9.2")
addSbtPlugin("com.wanari"       % "sbt-paradox-diagrams" % "0.1.4")
