addSbtPlugin("org.scalameta"  % "sbt-scalafmt"               % "2.6.1")
addSbtPlugin("com.github.sbt" % "sbt-site-paradox"           % "1.6.0")
addSbtPlugin("com.github.sbt" % "sbt-paradox-material-theme" % "0.7.0")
addSbtPlugin("io.kevinlee"    % "sbt-github-pages"           % "0.19.0")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin"            % "1.1.5")
addSbtPlugin("com.wanari"     % "sbt-paradox-diagrams"       % "0.1.4")
addSbtPlugin("com.github.sbt" % "sbt-release"                % "1.5.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp"                    % "2.3.1")
