addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-site"             % "1.4.1")
addSbtPlugin("io.kevinlee"      % "sbt-github-pages"     % "0.10.0")
addSbtPlugin("com.typesafe"     % "sbt-mima-plugin"      % "0.9.2")
addSbtPlugin("com.wanari"       % "sbt-paradox-diagrams" % "0.1.4")
addSbtPlugin("com.github.sbt"   % "sbt-release"          % "1.3.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"         % "3.10.0")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"              % "2.1.2")
