package org.appliedtopology.tda4j
package sset

import org.appliedtopology.tda4j.*

import scala.collection.mutable

/** A finite group as a multiplication table on the elements `0 until order`, with `0` the identity.
  *
  * Deliberately the dumbest possible representation: the nerve construction (`ClassifyingSpace`) only ever multiplies
  * and asks "is this the identity?", and a table makes both an array lookup. Fine up to a few hundred elements (S_5 has
  * 120: a 14,400-entry table).
  */
open class FiniteMonoid(val table: Array[Array[Int]], val names: IndexedSeq[String]):
  def order: Int = table.length
  def identity: Int = 0
  def multiply(a: Int, b: Int): Int = table(a)(b)

  /** Checks shape, range, identity and associativity; the empty list means the table really is a monoid. */
  def validateMonoid(): Seq[String] =
    val n = order
    if table.exists(_.length != n) then Seq("table is not square")
    else
      val range = table.flatten.filter(x => x < 0 || x >= n).take(1).map(x => s"entry $x out of range")
      val unit =
        (0 until n).filter(a => table(0)(a) != a || table(a)(0) != a).take(1).map(a => s"0 is not an identity at $a")
      val assoc =
        (for a <- 0 until n; b <- 0 until n; c <- 0 until n if table(table(a)(b))(c) != table(a)(table(b)(c))
        yield s"not associative at ($a,$b,$c)").take(1)
      range ++ unit ++ assoc

/** A finite monoid whose every element has an inverse. */
open class FiniteGroup(table: Array[Array[Int]], names: IndexedSeq[String]) extends FiniteMonoid(table, names):

  def inverse(a: Int): Int = table(a).indexOf(identity)

  /** Checks the monoid laws and that every element has an inverse; the empty list means the table is a group. */
  def validate(): Seq[String] =
    val monoid = validateMonoid()
    if monoid.nonEmpty then monoid
    else (0 until order).filter(a => !table(a).contains(identity)).take(1).map(a => s"$a has no inverse")

  /** The subgroup generated by `generators` (as a set of element indices; always contains the identity). */
  def subgroupGeneratedBy(generators: Iterable[Int]): Set[Int] =
    val members = mutable.LinkedHashSet[Int](identity)
    val queue = mutable.Queue[Int](identity)
    while queue.nonEmpty do
      val x = queue.dequeue()
      for g <- generators do
        val y = multiply(x, g)
        if members.add(y) then queue.enqueue(y)
    members.toSet

  /** The order of element `a`. */
  def elementOrder(a: Int): Int = Iterator.iterate(a)(multiply(_, a)).indexWhere(_ == identity) + 1

  /** Every nontrivial `p`-subgroup (order a power of the prime `p`), smallest first: the Brown poset `S_p(G)` once
    * ordered by inclusion (`FiniteCategory.fromPoset(g.pSubgroups(p), _ subsetOf _)`). Found by extending each
    * `p`-subgroup `Q` by a `p`-element `x` that normalizes it with `x^p` in `Q` -- every `p`-group arises this way from
    * a normal subgroup of index `p`.
    */
  def pSubgroups(p: Int): IndexedSeq[Set[Int]] =
    require(p > 1 && BigInt(p).isProbablePrime(certainty = 100), s"$p is not a prime")
    def isPowerOfP(k: Int): Boolean = k == 1 || (k % p == 0 && isPowerOfP(k / p))
    val pElements = (0 until order).filter(a => a != identity && isPowerOfP(elementOrder(a)))
    def power(a: Int, k: Int): Int = (1 until k).foldLeft(a)((x, _) => multiply(x, a))
    val found = mutable.LinkedHashSet.empty[Set[Int]]
    var frontier: Seq[Set[Int]] = Seq(Set(identity))
    while frontier.nonEmpty do
      val next = for
        q <- frontier
        x <- pElements
        if !q.contains(x) && q.contains(power(x, p)) && q.forall(y => q.contains(multiply(multiply(x, y), inverse(x))))
      yield subgroupGeneratedBy(q + x)
      frontier = next.distinct.filterNot(found.contains)
      found ++= frontier
    found.toIndexedSeq.sortBy(_.toList.sorted)(using Ordering.Implicits.seqOrdering[List, Int]).sortBy(_.size)

  /** Whether `subgroup` is elementary abelian of exponent `p`: abelian, with `x^p = 1` for every element. The
    * nontrivial ones among [[pSubgroups]] form Quillen's poset `A_p(G)`, homotopy equivalent to `S_p(G)`.
    */
  def isElementaryAbelian(subgroup: Set[Int], p: Int): Boolean =
    subgroup.forall(x => subgroup.forall(y => multiply(x, y) == multiply(y, x))) &&
      subgroup.forall(x => elementOrder(x) == 1 || elementOrder(x) == p)

object FiniteMonoid:

  /** The integers modulo `n` under multiplication (a monoid, not a group, unless `n <= 2`); element `k` is the residue
    * `k`, and the identity (residue 1) is re-indexed to `0` by swapping `0` and `1`... kept simple: elements are
    * `1, 0, 2, 3, ..., n-1` in that order, so the identity is index 0.
    */
  def multiplicativeResidues(n: Int): FiniteMonoid =
    require(n >= 2)
    val residue = (1 +: 0 +: (2 until n)).take(n).toVector
    val index = residue.zipWithIndex.toMap
    FiniteMonoid(Array.tabulate(n, n)((a, b) => index((residue(a) * residue(b)) % n)), residue.map(r => s"$r"))

  /** The `rows x columns` rectangular band, `(a, b)(c, d) = (a, d)`, with an identity adjoined (index 0); element `(a,
    * b)` is index `1 + a * columns + b`. Its classifying space is a wedge of `(rows - 1)(columns - 1)` two-spheres: a
    * finite monoid whose nerve has free homology in degree 2 and none above, which no finite group's has.
    */
  def rectangularBand(rows: Int, columns: Int): FiniteMonoid =
    require(rows >= 1 && columns >= 1, s"a rectangular band needs rows, columns >= 1, got $rows x $columns")
    val size = 1 + rows * columns
    def row(x: Int) = (x - 1) / columns
    def column(x: Int) = (x - 1) % columns
    FiniteMonoid(
      Array.tabulate(size, size)((x, y) =>
        if x == 0 then y else if y == 0 then x else 1 + row(x) * columns + column(y)
      ),
      "1" +: IndexedSeq.tabulate(rows * columns)(i => s"(${i / columns},${i % columns})")
    )

  /** The Rees matrix semigroup `M[G; rows, columns; P]` with an identity adjoined (index 0): elements `(i, g, λ)` for
    * `i < rows`, `g` in `group`, `λ < columns`, multiplied by `(i, g, λ)(j, h, μ) = (i, g·P(λ)(j)·h, μ)`, where the
    * sandwich matrix `sandwich(λ)(i)` holds element indices of `group`. Element `(i, g, λ)` is index `1 + (i *
    * |G| + g) * columns + λ`. Every finite completely simple semigroup is one of these; `group` trivial gives the
    * rectangular band.
    */
  def reesMatrix(group: FiniteGroup, rows: Int, columns: Int, sandwich: IndexedSeq[IndexedSeq[Int]]): FiniteMonoid =
    require(rows >= 1 && columns >= 1, s"a Rees matrix semigroup needs rows, columns >= 1, got $rows x $columns")
    require(
      sandwich.length == columns && sandwich.forall(r => r.length == rows && r.forall(g => g >= 0 && g < group.order)),
      s"the sandwich matrix must be columns x rows ($columns x $rows) with entries in 0 until ${group.order}"
    )
    val n = group.order
    val size = 1 + rows * n * columns
    def index(i: Int, g: Int, l: Int) = 1 + (i * n + g) * columns + l
    def decode(x: Int) = ((x - 1) / columns / n, ((x - 1) / columns) % n, (x - 1) % columns)
    FiniteMonoid(
      Array.tabulate(size, size) { (x, y) =>
        if x == 0 then y
        else if y == 0 then x
        else
          val (i, g, l) = decode(x)
          val (j, h, mu) = decode(y)
          index(i, group.multiply(group.multiply(g, sandwich(l)(j)), h), mu)
      },
      "1" +: (1 until size).map { x =>
        val (i, g, l) = decode(x)
        s"($i,${group.names(g)},$l)"
      }
    )

object FiniteGroup:

  def cyclic(n: Int): FiniteGroup =
    require(n >= 1)
    FiniteGroup(Array.tabulate(n, n)((a, b) => (a + b) % n), IndexedSeq.tabulate(n)(i => s"g^$i"))

  /** Direct product; element `(a, b)` is indexed `a * order(h) + b`, so the identity stays `0`. */
  def product(g: FiniteGroup, h: FiniteGroup): FiniteGroup =
    val m = h.order
    FiniteGroup(
      Array.tabulate(g.order * m, g.order * m)((x, y) => g.multiply(x / m, y / m) * m + h.multiply(x % m, y % m)),
      IndexedSeq.tabulate(g.order * m)(x => s"(${g.names(x / m)},${h.names(x % m)})")
    )

  /** The group generated by permutations of `0 until degree` (each given as the image list `p(0), p(1), ...`), together
    * with the generators' element indices. Composition is `(p * q)(x) = p(q(x))`.
    */
  def permutationGroup(degree: Int, generators: Seq[Seq[Int]]): (FiniteGroup, Seq[Int]) =
    val id = Vector.range(0, degree)
    def compose(p: Vector[Int], q: Vector[Int]): Vector[Int] = q.map(p)
    val gens = generators.map(_.toVector)
    val elements = mutable.ArrayBuffer[Vector[Int]](id)
    val index = mutable.HashMap[Vector[Int], Int](id -> 0)
    var next = 0
    while next < elements.length do
      for g <- gens do
        val y = compose(elements(next), g)
        if !index.contains(y) then
          index(y) = elements.length
          elements += y
      next += 1
    val table = Array.tabulate(elements.length, elements.length)((a, b) => index(compose(elements(a), elements(b))))
    val names = elements.map(p => cycleNotation(p)).toIndexedSeq
    (FiniteGroup(table, names), gens.map(g => index.getOrElse(g, throw IllegalArgumentException("not a permutation"))))

  /** The symmetric group S_n, generated by the transposition (0 1) and the n-cycle. */
  def symmetric(n: Int): FiniteGroup =
    require(n >= 2)
    val transposition = Vector.range(0, n).updated(0, 1).updated(1, 0)
    val cycle = Vector.tabulate(n)(i => (i + 1) % n)
    permutationGroup(n, Seq(transposition, cycle))._1

  /** The alternating group A_n (`n >= 3`), generated by the 3-cycles `(0 1 k)`. */
  def alternating(n: Int): FiniteGroup =
    require(n >= 3, s"the alternating group needs n >= 3, got $n")
    val threeCycles = (2 until n).map(k => Vector.range(0, n).updated(0, 1).updated(1, k).updated(k, 0))
    permutationGroup(n, threeCycles)._1

  /** The general linear group GL(n, p) over the prime field `F_p`, as permutations of the `p^n - 1` nonzero vectors
    * (vector `v_0 + v_1 p + ... + v_{n-1} p^{n-1}` is point `v - 1`); generated by the elementary transvections and,
    * for `p > 2`, the diagonal matrix with a primitive root in the corner. Order
    * `(p^n - 1)(p^n - p)...(p^n - p^{n-1})`: GL(3, 2) has 168 elements.
    */
  def generalLinear(n: Int, p: Int): FiniteGroup =
    require(n >= 1, s"n must be >= 1, got $n")
    require(p > 1 && BigInt(p).isProbablePrime(certainty = 100), s"$p is not a prime")
    val size = BigInt(p).pow(n).toInt
    def digits(v: Int): Vector[Int] = Vector.tabulate(n)(i => (v / BigInt(p).pow(i).toInt) % p)
    def number(d: Vector[Int]): Int = d.zipWithIndex.map((x, i) => x * BigInt(p).pow(i).toInt).sum
    def asPermutation(matrix: Vector[Int] => Vector[Int]): Seq[Int] =
      (1 until size).map(v => number(matrix(digits(v))) - 1)
    val transvections =
      for i <- 0 until n; j <- 0 until n if i != j
      yield asPermutation(d => d.updated(i, (d(i) + d(j)) % p))
    val primitiveRoot = (1 until p).find(r => (1 until p - 1).forall(k => BigInt(r).modPow(k, p) != 1)).get
    val diagonal = if p > 2 then Seq(asPermutation(d => d.updated(0, (d(0) * primitiveRoot) % p))) else Seq.empty
    permutationGroup(size - 1, transvections ++ diagonal)._1

  /** The element of `g` (a permutation group built by [[permutationGroup]]) that has this image list. */
  def elementOfPermutation(g: FiniteGroup, p: Seq[Int]): Int =
    val wanted = cycleNotation(p.toVector)
    val i = g.names.indexOf(wanted)
    require(i >= 0, s"$wanted is not an element of the group")
    i

  private def cycleNotation(p: Vector[Int]): String =
    val seen = Array.fill(p.length)(false)
    val cycles = for
      start <- p.indices
      if !seen(start) && p(start) != start
    yield
      val cycle = Iterator
        .iterate(start)(p)
        .takeWhile { x =>
          val fresh = !seen(x); seen(x) = true; fresh
        }
        .toList
      cycle.mkString("(", " ", ")")
    if cycles.isEmpty then "e" else cycles.mkString
