package org.appliedtopology.tda4j
package tutorial

import java.util.Random

/** The point clouds the tutorials share, generated by seeded code so their provenance is part of the repository.
  * `TutorialDataSpec` regenerates every file and compares it with the committed copy under `_docs/tutorials/data/`; to
  * change a dataset, change it HERE and run `sbt "Test/runMain org.appliedtopology.tda4j.tutorial.TutorialData"` to
  * rewrite the files. Coordinates are rounded to four decimals, so the files are stable text.
  */
object TutorialData:

  private def round4(x: Double): Double = math.round(x * 10000.0) / 10000.0

  private def csv(points: Seq[Seq[Double]]): String =
    points.map(_.map(x => f"${round4(x)}%.4f").mkString(", ")).mkString("", "\n", "\n")

  /** `n` points on the unit circle at random angles, each coordinate perturbed by Gaussian noise of size `noise`. */
  def noisyCircle(n: Int, noise: Double, seed: Long): Seq[Seq[Double]] =
    val rng = new Random(seed)
    Seq.fill(n) {
      val a = 2 * math.Pi * rng.nextDouble()
      Seq(math.cos(a) + noise * rng.nextGaussian(), math.sin(a) + noise * rng.nextGaussian())
    }

  /** A noisy unit circle plus `outliers` further points scattered uniformly over the square `[-half, half]^2` around
    * it.
    */
  def circleWithOutliers(n: Int, noise: Double, outliers: Int, half: Double, seed: Long): Seq[Seq[Double]] =
    val rng = new Random(seed)
    val ring = Seq.fill(n) {
      val a = 2 * math.Pi * rng.nextDouble()
      Seq(math.cos(a) + noise * rng.nextGaussian(), math.sin(a) + noise * rng.nextGaussian())
    }
    val background = Seq.fill(outliers)(Seq(half * (2 * rng.nextDouble() - 1), half * (2 * rng.nextDouble() - 1)))
    ring ++ background

  /** Gerono's lemniscate (a figure eight), `(cos t, sin t cos t)`, with Gaussian noise. */
  def figureEight(n: Int, noise: Double, seed: Long): Seq[Seq[Double]] =
    val rng = new Random(seed)
    Seq.fill(n) {
      val t = 2 * math.Pi * rng.nextDouble()
      Seq(math.cos(t) + noise * rng.nextGaussian(), math.sin(t) * math.cos(t) + noise * rng.nextGaussian())
    }

  /** The flat torus in R^4, `(cos a, sin a, cos b, sin b)`, at random angles `(a, b)`. */
  def flatTorus(n: Int, seed: Long): Seq[Seq[Double]] =
    val rng = new Random(seed)
    Seq.fill(n) {
      val a = 2 * math.Pi * rng.nextDouble()
      val b = 2 * math.Pi * rng.nextDouble()
      Seq(math.cos(a), math.sin(a), math.cos(b), math.sin(b))
    }

  /** file name -> exact file contents */
  def files: Map[String, String] = Map(
    "noisy-circle.csv" -> csv(noisyCircle(60, 0.05, 1L)),
    "circle-with-outliers.csv" -> csv(circleWithOutliers(70, 0.03, 25, 2.0, 7L)),
    "figure-eight.csv" -> csv(figureEight(70, 0.02, 3L)),
    "flat-torus.csv" -> csv(flatTorus(120, 4L))
  )

  def main(args: Array[String]): Unit =
    files.foreach { (name, text) =>
      java.nio.file.Files.writeString(java.nio.file.Paths.get("_docs/tutorials/data", name), text)
      println(s"wrote _docs/tutorials/data/$name")
    }
