package org.appliedtopology.tda4j
package tutorial

import org.specs2.mutable.Specification

/** The committed data files must be exactly what the seeded generator produces. */
class TutorialDataSpec extends Specification:
  "the tutorial data files" should {
    TutorialData.files.foreach { (name, expected) =>
      s"$name match their generator" in {
        java.nio.file.Files.readString(java.nio.file.Paths.get("_docs/tutorials/data", name)) must beEqualTo(expected)
      }
    }
    "be regenerated by TutorialData.main if the generator changes" in { TutorialData.files.size must beEqualTo(5) }
  }
