name: Docs

on:
  push:
    branches:
      - scala

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/gh-pages' && github.ref != 'gh-pages'
    steps:
      - uses: actions/checkout@v2
      - name: Compile and publish docs
        run: sbt makeSite publishToGitHubPages
