name: Test and Lint

on:
  push:
    branches:
      - scala
  pull_request:
    branches:
      - scala

jobs:
  test:
    runs-on: ubuntu-latest
    environment: codecov
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt clean coverage test coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck