name: Test

on:
  push:
    branches:
      - scala
  pull_request:
    branches:
      - scala

jobs:
  test:
    runs-on: ubuntu-latest
    environment: codecov
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt clean test
