name: Test

on:
  push:
    branches:
      - scala
  pull_request:
    branches:
      - scala

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Run tests
        run: ./mill --no-server --disable-ticker tda4j.__.test tda4j.__.htmlReport
      - name: Save reports
        uses: actions/upload-artifact@v7
        with:
          name: scoverage-report
          path: out/tda4j/3.8.4/scoverage/htmlReport.dest
